//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF370_2023_Web_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Application()
        {
            this.ShortLists = new HashSet<ShortList>();
        }
    
        public int ApplicationID { get; set; }
        public int JobOppID { get; set; }
        public int ApplicantID { get; set; }
        public int ApplicationStatusID { get; set; }
    
        public virtual Applicant Applicant { get; set; }
        public virtual ApplicationStatu ApplicationStatu { get; set; }
        public virtual JobOpportunity JobOpportunity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShortList> ShortLists { get; set; }
    }
}
