//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF370_2023_Web_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public int AuditLogID { get; set; }
        public int UserID { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public string AuditName { get; set; }
    
        public virtual User User { get; set; }
    }
}
