//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF370_2023_Web_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoursePrice
    {
        public int PriceID { get; set; }
        public double Price { get; set; }
        public int CourseID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
