//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF370_2023_Web_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterviewSlot
    {
        public int InterviewSlotID { get; set; }
        public int ShortListID { get; set; }
        public System.DateTime InterviewDate { get; set; }
        public System.TimeSpan InterviewTime { get; set; }
        public int InterviewCode { get; set; }
    
        public virtual ShortList ShortList { get; set; }
    }
}
