//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF370_2023_Web_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobOpportunity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobOpportunity()
        {
            this.Applications = new HashSet<Application>();
        }
    
        public int JobOppID { get; set; }
        public string JobOppTitle { get; set; }
        public string JobOppDescription { get; set; }
        public string JobOppRequirements { get; set; }
        public int DepartmentID { get; set; }
        public System.DateTime JobOppDeadline { get; set; }
        public int WorkTypeID { get; set; }
        public int JobOppStatusID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application> Applications { get; set; }
        public virtual Department Department { get; set; }
        public virtual JobOppStatu JobOppStatu { get; set; }
        public virtual WorkType WorkType { get; set; }
    }
}
