//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF370_2023_Web_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LessonResource
    {
        public int ResourceID { get; set; }
        public int LessonID { get; set; }
        public string ResourceName { get; set; }
        public byte[] ResourceFile { get; set; }
    
        public virtual Lesson Lesson { get; set; }
    }
}
