//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF370_2023_Web_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maintenance
    {
        public int MaintenanceID { get; set; }
        public int UserID { get; set; }
        public int MaintenanceTypeID { get; set; }
        public int MaintenanceStatusID { get; set; }
        public int MaintenancePriorityID { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public System.DateTime DateLogged { get; set; }
        public Nullable<System.DateTime> DateResolved { get; set; }
        public byte[] Image { get; set; }
    
        public virtual MaintenancePriority MaintenancePriority { get; set; }
        public virtual MaintenanceStatu MaintenanceStatu { get; set; }
        public virtual MaintenanceType MaintenanceType { get; set; }
        public virtual User User { get; set; }
    }
}
