//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF370_2023_Web_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentID { get; set; }
        public int CartID { get; set; }
        public double Amount { get; set; }
        public int pf_payment_id { get; set; }
        public string payment_status { get; set; }
    
        public virtual Cart Cart { get; set; }
    }
}
